name: call_manager
description: Call Manager in Flutter
version: 2.6.0+45
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  direct_dialer:
    git: https://github.com/GroovinChip/direct_dialer.git
  url_launcher: ^6.0.3
  flutter_local_notifications: ^5.0.0+3
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.7
  package_info: ^2.0.0
  permission_handler: ^7.0.0
  groovin_widgets: ^2.0.0
  contacts_service: ^0.6.1
  flutter_typeahead: ^3.1.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  google_fonts: ^2.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  timezone: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.7.2"
  dart_code_metrics: ^3.0.0

flutter_icons:
  android: true
  #image_path: "assets/icon/call_manager_app_icon.png"
  #adaptive_icon_background: "#1976D2"

flutter:

  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500