name: call_manager
description: Call Manager in Flutter
version: 2.8.1+50
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bluejay: ^1.3.0
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  direct_dialer: ^1.0.1+1
  url_launcher: ^6.0.3
  flutter_local_notifications: ^6.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.2.0
  package_info: ^2.0.1
  permission_handler: ^8.0.0+2
  groovin_widgets: ^2.0.0
  contacts_service: ^0.6.1
  flutter_typeahead: ^3.1.3
  rxdart: ^0.27.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  google_fonts: ^2.1.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  timezone: any
  wiredash: ^0.7.0
  macos_ui: ^0.2.2
  google_sign_in_dartio:
    git:
      url: git@github.com:GroovinChip/firebase_dart_sdk.git
      path: google_sign_in_dart
      ref: null_safety
  bitsdojo_window: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.7.2"
  dart_code_metrics: ^3.3.2

flutter_icons:
  android: true
  #image_path: "assets/icon/call_manager_app_icon.png"
  #adaptive_icon_background: "#1976D2"

flutter:

  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500