name: call_manager
description: Call Manager in Flutter
version: 2.4.0+35
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  datetime_picker_formfield: any
  call_number:
    path: ../../packages_and_plugins/call_number
  url_launcher: ^5.2.5
  flutter_local_notifications: ^4.0.1+2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0+1
  package_info: ^0.4.3+4
  permission_handler: ^5.0.1+1
  groovin_widgets: ^1.6.1
  contacts_service: ^0.4.6
  flutter_typeahead: ^2.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.4
  provider: ^5.0.0
  google_fonts: ^1.1.2
  material_design_icons_flutter: ^4.0.5955

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  dart_code_metrics: ^2.4.1

flutter_icons:
  android: true
  image_path: "assets/icon/call_manager_app_icon.png"
  adaptive_icon_background: "#1976D2"

flutter:

  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500